version: "3.9"

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:latest
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    container_name: myapp
    ports:
      - "9012:9012"
    depends_on:
      db:
        condition: service_healthy
    restart: always
  db:
    image: postgres:16-alpine
    container_name: myapp-db
    env_file:
      - .env
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tvshow"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
